web-admin:
  image: apisearch/web-admin
  ports:
   - "7010:8080"
  links:
   - apisearch
  restart: always
apisearch:
  image: apisearch/apisearch
  command: server
  ports:
   - "7011:8080"
  links:
   - elasticsearch
  restart: always
import-products:
  image: apisearch/apisearch
  command: import
  links:
   - elasticsearch
create-index:
  image: apisearch/apisearch:latest
  command: createIndex
  links:
   - elasticsearch
elasticsearch:
  image: apisearch/elasticsearch
  volumes:
   - /mnt/apisearch/elasticsearch:/usr/share/elasticsearch/data
  restart: always
